<?php

namespace Tests\Unit\Diagnosis;

use PHPUnit\Framework\TestCase;

class TransformationImplementationPlanAutoserviceUiContractTest
    extends TestCase
{
    private function root(): string
    {
        return dirname(__DIR__, 3);
    }

    private function vue(): string
    {
        return file_get_contents(
            $this->root()
            .'/resources/js/pages/Admin/DiagnosisRequests/'
            .'ImplementationPlan.vue'
        );
    }

    public function test_admin_is_supervisor_not_manual_plan_builder(): void
    {
        $source = $this->vue();

        foreach ([
            '1. Fuente del Plan',
            '2. Plan generado',
            '3. Modalidades de ejecución',
            '4. Inversión y tiempo',
            '5. Hitos y condiciones',
            '6. Presentación',
            'El administrador revisa y supervisa',
        ] as $required) {
            $this->assertStringContainsString(
                $required,
                $source
            );
        }

        foreach ([
            'Agregar fase',
            'Guardar modalidad',
            'Guardar precio/tiempo en DOP',
            'Agregar/actualizar hito',
            'Marcar como aceptado',
            'phaseCapabilities',
            'estimateForms',
            'milestoneForms',
        ] as $forbidden) {
            $this->assertStringNotContainsString(
                $forbidden,
                $source
            );
        }
    }

    public function test_empty_legacy_draft_can_be_autogenerated(): void
    {
        $source = $this->vue();

        $this->assertStringContainsString(
            'Borrador anterior sin estructura',
            $source
        );

        $this->assertStringContainsString(
            'Generar estructura automática',
            $source
        );

        $this->assertStringContainsString(
            'props.endpoints.create',
            $source
        );
    }

    public function test_three_modalities_are_explained_before_selection(): void
    {
        $source = $this->vue();

        foreach ([
            'Modalidades de ejecución',
            'Incluye',
            'LAUDA',
            'Cliente',
            'modality_options',
            'Modalidad recomendada',
            'Modalidad contratada',
        ] as $required) {
            $this->assertStringContainsString(
                $required,
                $source
            );
        }

        $this->assertStringNotContainsString(
            '@click="saveModality"',
            $source
        );
    }

    public function test_commercial_comparison_waits_for_real_estimates(): void
    {
        $source = $this->vue();

        foreach ([
            'modalityScenarios',
            'scenario.complete',
            'Pendiente',
            'La matriz comercial todavía debe',
            'precio y tiempo',
        ] as $required) {
            $this->assertStringContainsString(
                $required,
                $source
            );
        }
    }

    public function test_tenant_owns_acceptance(): void
    {
        $source = $this->vue();

        // Admin sí puede presentar el Plan.
        $this->assertStringContainsString(
            'function presentPlan()',
            $source
        );

        $this->assertStringContainsString(
            'props.endpoints.present',
            $source
        );

        // Admin ya no puede aceptar el Plan.
        $this->assertStringNotContainsString(
            'function acceptPlan(',
            $source
        );

        $this->assertStringNotContainsString(
            'Marcar como aceptado',
            $source
        );

        $this->assertStringNotContainsString(
            '@click="acceptPlan"',
            $source
        );
    }

}
