<script setup lang="ts">
import { computed } from 'vue';
import { Head, Link, router, usePage } from '@inertiajs/vue3';
import {
    ArrowLeft,
    CheckCircle2,
    Clock3,
    FileText,
    RefreshCcw,
    Send,
    Sparkles,
} from 'lucide-vue-next';

import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem } from '@/types';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';

type Initiative = {
    id: string | number | null;
    priority: string | null;
    title: string | null;
    objective: string | null;
    actions: string[];
    owner_role: string | null;
    dependencies: string[];
    success_metrics: string[];
};

type Capability = {
    id: number;
    sequence: number;
    capability_key: string;
    capability_label: string;
    summary: string | null;
    kind: 'professional_service';
    includes: string[];
    requires_lauda_review: boolean;
    commercial_readiness: string | null;
    activation_policy: string | null;
    recommendation_basis: string | null;
};

type Phase = {
    id: number;
    sequence: number;
    name: string;
    objective: string | null;
    horizon: string | null;
    initiative_ids: Array<string | number>;
    initiatives: Initiative[];
    dependencies: string[];
    deliverables: string[];
    autogenerated: boolean;
    capabilities: Capability[];
};

const props = defineProps<{
    contact: {
        id: number;
        name: string;
        company: string | null;
        email: string;
    };
    assessment: {
        id: number;
        organization_name: string;
    };
    roadmap: {
        id: number;
        version: number;
        published_at: string | null;
    } | null;
    tenant_validation: {
        deliverable_id: number | null;
        version: number | null;
        validated: boolean;
        validated_at: string | null;
    };
    plan: {
        id: number;
        version: number;
        status: string;
        source_type: string;
        source_label: string;
        autogeneration: Record<string, unknown> | null;
        presented_at: string | null;
        legacy_execution_available: boolean;
        phases: Phase[];
    } | null;
    capability_options: Array<Record<string, unknown>>;
    endpoints: {
        back: string;
        create: string;
        regenerate: string;
        phase_store: string;
        present: string;
    };
}>();

const page = usePage();
const errors = computed(
    () => (page.props.errors ?? {}) as Record<string, string>,
);
const planValidated = computed(
    () =>
        props.plan !== null &&
        props.tenant_validation?.deliverable_id === props.plan.id &&
        props.tenant_validation?.validated === true,
);
const isDraft = computed(
    () => props.plan?.status === 'draft' && !planValidated.value,
);
const phases = computed(() => props.plan?.phases ?? []);

const breadcrumbs: BreadcrumbItem[] = [
    { title: 'Inicio', href: '/app' },
    { title: 'Diagnóstico 360', href: `/admin/diagnosis-requests/${props.contact.id}` },
    { title: 'Plan de Implementación', href: `/admin/diagnosis-requests/${props.contact.id}/implementation-plan` },
];

function statusLabel(status: string): string {
    return ({
        draft: 'Borrador',
        presented: 'Presentado',
        accepted: 'Histórico',
        active: 'Histórico',
        completed: 'Completado',
        cancelled: 'Cancelado',
    } as Record<string, string>)[status] ?? status;
}

function createOrGeneratePlan(): void {
    router.post(props.endpoints.create, {}, { preserveScroll: true });
}

function regeneratePlanStructure(): void {
    if (!window.confirm('¿Regenerar estructura desde la fuente? Se reemplazará la estructura consultiva del borrador actual.')) {
        return;
    }

    router.post(props.endpoints.regenerate, {}, { preserveScroll: true });
}

function presentPlan(): void {
    if (!window.confirm('¿Presentar este Plan de Implementación al tenant para su revisión?')) {
        return;
    }

    router.post(props.endpoints.present, {}, { preserveScroll: true });
}
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head title="Plan de Implementación" />

        <div class="mx-auto w-full max-w-[1600px] space-y-6 p-4 sm:p-6 lg:p-8">
            <div class="flex flex-wrap items-center justify-between gap-4">
                <div>
                    <p class="text-xs font-black tracking-widest text-primary uppercase">
                        Transformación 360 · Supervisor
                    </p>
                    <h1 class="mt-1 text-2xl font-black">Plan de Implementación</h1>
                    <p class="mt-2 text-sm text-muted-foreground">
                        {{ contact.company || assessment.organization_name }} · Entregable consultivo gratuito
                    </p>
                </div>

                <Button as-child variant="outline">
                    <Link :href="endpoints.back">
                        <ArrowLeft class="mr-2 size-4" />
                        Volver
                    </Link>
                </Button>
            </div>

            <Card v-if="Object.keys(errors).length" class="border-destructive/30 bg-destructive/5">
                <CardContent class="space-y-1 p-5 text-sm text-destructive">
                    <p v-for="(message, key) in errors" :key="key">{{ message }}</p>
                </CardContent>
            </Card>

            <Card v-if="planValidated" class="border-emerald-200 bg-emerald-50">
                <CardContent class="p-5 text-sm text-emerald-900">
                    <p class="font-black">Versión validada por el tenant y cerrada</p>
                    <p class="mt-1">
                        Este Plan no puede regenerarse ni volver a presentarse como la misma versión. Cualquier cambio debe gestionarse mediante una nueva versión documental.
                    </p>
                </CardContent>
            </Card>

            <template v-if="!plan">
                <Card>
                    <CardHeader>
                        <CardTitle>Generar Plan de Implementación</CardTitle>
                        <CardDescription>
                            Se construirá automáticamente desde el Roadmap publicado o, si todavía no existe, desde el diagnóstico oficial.
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <Button @click="createOrGeneratePlan">
                            <Sparkles class="mr-2 size-4" />
                            Generar Plan consultivo
                        </Button>
                    </CardContent>
                </Card>
            </template>

            <template v-else>
                <div class="grid gap-6 xl:grid-cols-2">
                    <Card>
                        <CardHeader>
                            <CardTitle>1. Fuente del Plan</CardTitle>
                            <CardDescription>
                                Trazabilidad del documento que alimentó la estructura.
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="space-y-4 text-sm">
                            <div class="flex flex-wrap gap-2">
                                <Badge variant="outline">V{{ plan.version }}</Badge>
                                <Badge variant="outline">{{ statusLabel(plan.status) }}</Badge>
                            </div>
                            <div class="rounded-xl border bg-muted/20 p-4">
                                <p class="text-xs font-bold uppercase text-muted-foreground">Fuente</p>
                                <p class="mt-1 font-semibold">{{ plan.source_label }}</p>
                                <p v-if="plan.source_type === 'internal_assessment'" class="mt-2 text-muted-foreground">
                                    Diagnóstico oficial · snapshot interno
                                </p>
                            </div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>2. Alcance consultivo</CardTitle>
                            <CardDescription>
                                Este documento explica qué transformar y cómo organizar la ejecución.
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="space-y-3 text-sm leading-6 text-muted-foreground">
                            <p>
                                El Plan no selecciona modalidad, no cotiza la ejecución, no crea hitos de facturación y no constituye una contratación comercial.
                            </p>
                            <p>
                                Las soluciones LAUDAAPI se contratan y activan fuera de este Plan. Aquí solo se conservan capacidades profesionales de transformación cuando sean necesarias.
                            </p>
                        </CardContent>
                    </Card>
                </div>

                <Card>
                    <CardHeader>
                        <CardTitle>3. Plan generado</CardTitle>
                        <CardDescription>
                            Fases, objetivos, iniciativas, actividades, responsables, dependencias, entregables y horizonte técnico.
                        </CardDescription>
                    </CardHeader>
                    <CardContent class="space-y-5">
                        <div v-if="!phases.length" class="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">
                            <p class="font-bold text-foreground">Borrador anterior sin estructura</p>
                            <p class="mt-1">Genera la estructura automática desde la fuente oficial.</p>
                            <Button v-if="isDraft" class="mt-4" @click="createOrGeneratePlan">
                                <Sparkles class="mr-2 size-4" />
                                Generar estructura automática
                            </Button>
                        </div>

                        <article v-for="phase in phases" :key="phase.id" class="rounded-2xl border p-5">
                            <div class="flex flex-wrap items-start justify-between gap-3">
                                <div>
                                    <p class="text-xs font-black tracking-widest text-primary uppercase">Fase {{ phase.sequence }}</p>
                                    <h3 class="mt-1 text-lg font-black">{{ phase.name }}</h3>
                                    <p v-if="phase.objective" class="mt-2 max-w-4xl text-sm leading-6 text-muted-foreground">{{ phase.objective }}</p>
                                </div>
                                <Badge v-if="phase.horizon" variant="outline">
                                    <Clock3 class="mr-1 size-3" />{{ phase.horizon }}
                                </Badge>
                            </div>

                            <div v-if="phase.initiatives.length" class="mt-5 space-y-3">
                                <p class="text-xs font-black uppercase tracking-wider">Iniciativas y actividades</p>
                                <div v-for="initiative in phase.initiatives" :key="String(initiative.id ?? initiative.title)" class="rounded-xl bg-muted/30 p-4">
                                    <div class="flex flex-wrap items-center gap-2">
                                        <p class="font-bold">{{ initiative.title || 'Iniciativa' }}</p>
                                        <Badge v-if="initiative.priority" variant="outline">{{ initiative.priority }}</Badge>
                                    </div>
                                    <p v-if="initiative.objective" class="mt-2 text-sm text-muted-foreground">{{ initiative.objective }}</p>
                                    <ul v-if="initiative.actions.length" class="mt-3 list-disc space-y-1 pl-5 text-sm">
                                        <li v-for="action in initiative.actions" :key="action">{{ action }}</li>
                                    </ul>
                                    <p v-if="initiative.owner_role" class="mt-3 text-xs text-muted-foreground">
                                        Responsable sugerido: <strong class="text-foreground">{{ initiative.owner_role }}</strong>
                                    </p>
                                </div>
                            </div>

                            <div class="mt-5 grid gap-4 md:grid-cols-2">
                                <div class="rounded-xl border p-4">
                                    <p class="text-xs font-black uppercase">Dependencias</p>
                                    <ul v-if="phase.dependencies.length" class="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                                        <li v-for="item in phase.dependencies" :key="item">{{ item }}</li>
                                    </ul>
                                    <p v-else class="mt-2 text-sm text-muted-foreground">Sin dependencias adicionales registradas.</p>
                                </div>
                                <div class="rounded-xl border p-4">
                                    <p class="text-xs font-black uppercase">Entregables</p>
                                    <ul v-if="phase.deliverables.length" class="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                                        <li v-for="item in phase.deliverables" :key="item">{{ item }}</li>
                                    </ul>
                                    <p v-else class="mt-2 text-sm text-muted-foreground">Se definen según las iniciativas de esta fase.</p>
                                </div>
                            </div>

                            <div class="mt-5">
                                <p class="text-xs font-black uppercase">Apoyo profesional sugerido</p>
                                <div v-if="phase.capabilities.length" class="mt-2 grid gap-3 md:grid-cols-2">
                                    <div
                                        v-for="capability in phase.capabilities"
                                        :key="capability.id"
                                        class="rounded-xl border p-4"
                                    >
                                        <div class="flex flex-wrap items-center gap-2">
                                            <p class="font-bold">
                                                {{ capability.capability_label }}
                                            </p>

                                            <Badge variant="secondary">
                                                Servicio profesional
                                            </Badge>

                                            <Badge
                                                v-if="capability.activation_policy === 'implementation_only'"
                                                variant="outline"
                                            >
                                                Se define y cotiza en Implementación
                                            </Badge>
                                        </div>

                                        <p
                                            v-if="capability.summary"
                                            class="mt-2 text-sm leading-6 text-muted-foreground"
                                        >
                                            {{ capability.summary }}
                                        </p>

                                        <div
                                            v-if="
                                                capability.recommendation_basis
                                                && capability.recommendation_basis !== 'professional_transformation_capability'
                                            "
                                            class="mt-4 rounded-lg bg-muted/30 p-3"
                                        >
                                            <p class="text-xs font-black uppercase">
                                                Fundamento de recomendación
                                            </p>
                                            <p class="mt-1 text-sm leading-6 text-muted-foreground">
                                                {{ capability.recommendation_basis }}
                                            </p>
                                        </div>

                                        <div
                                            v-if="capability.includes.length"
                                            class="mt-4"
                                        >
                                            <p class="text-xs font-black uppercase">
                                                Alcance incluido
                                            </p>
                                            <ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                                                <li
                                                    v-for="item in capability.includes"
                                                    :key="item"
                                                >
                                                    {{ item }}
                                                </li>
                                            </ul>
                                        </div>

                                        <p
                                            v-if="capability.activation_policy === 'implementation_only'"
                                            class="mt-4 text-xs leading-5 text-muted-foreground"
                                        >
                                            Esta capacidad no se activa desde el ciclo consultivo gratuito. Su ejecución, alcance final, tiempo y precio se definen en la Etapa de Implementación.
                                        </p>
                                    </div>
                                </div>
                                <p v-else class="mt-2 text-sm text-muted-foreground">
                                    Esta fase no requiere un servicio profesional adicional.
                                </p>
                            </div>
                        </article>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle>4. Presentación</CardTitle>
                        <CardDescription>
                            Presenta el documento al tenant para lectura y revisión. Una vez validada la versión, queda cerrada y no puede volver a presentarse.
                        </CardDescription>
                    </CardHeader>
                    <CardContent class="flex flex-wrap gap-3">
                        <Button v-if="isDraft" variant="outline" @click="regeneratePlanStructure">
                            <RefreshCcw class="mr-2 size-4" />
                            Regenerar estructura desde la fuente
                        </Button>
                        <Button v-if="isDraft && phases.length" @click="presentPlan">
                            <Send class="mr-2 size-4" />
                            Presentar al tenant
                        </Button>
                        <div v-if="plan.presented_at" class="flex items-center gap-2 text-sm font-semibold text-emerald-700">
                            <CheckCircle2 class="size-4" />
                            Plan presentado
                        </div>
                    </CardContent>
                </Card>
            </template>
        </div>
    </AppLayout>
</template>
