<script setup lang="ts">
import { computed } from 'vue';
import { Head, Link, router, usePage } from '@inertiajs/vue3';
import {
    ArrowLeft,
    CheckCircle2,
    Clock3,
    FileText,
    Gauge,
    Layers3,
    LockKeyhole,
    Route,
    Send,
    Sparkles,
    UserRoundCheck,
    UsersRound,
} from 'lucide-vue-next';

import AppLayout from '@/layouts/AppLayout.vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';

type Estimate = {
    modality: string;
    price_amount: number;
    currency: string;
    estimated_duration_value: number;
    estimated_duration_unit: string;
};

type Capability = {
    id: number;
    sequence: number;
    capability_key: string;
    capability_label: string;
    summary: string | null;
    kind: string | null;
    service_key: string | null;
    subscription_candidate: boolean;
    includes: string[];
};

type Milestone = {
    id: number;
    sequence: number;
    name: string;
    modality: string;
    modality_label: string;
    billing_percentage: number;
    billing_amount: number;
    currency: string;
    billing_status: string;
};

type Phase = {
    id: number;
    sequence: number;
    name: string;
    objective: string | null;
    horizon: string | null;
    initiative_ids: string[];
    dependencies: string[];
    deliverables: string[];
    autogenerated: boolean;
    capabilities: Capability[];
    estimate: Estimate | null;
    estimates: Estimate[];
    milestones: Milestone[];
};

type ModalityOption = {
    key: string;
    label: string;
    description: string | null;
    lauda_role: string | null;
    client_role: string | null;
    includes: string[];
};

const props = defineProps<{
    contact: {
        id: number;
        company: string | null;
    };
    assessment: {
        id: number;
        organization_name: string;
    };
    roadmap: {
        id: number;
        version: number;
        published_at: string | null;
    } | null;
    plan: {
        id: number;
        version: number;
        status: string;
        source_type: string;
        autogeneration: {
            generator?: string;
            generated_at?: string;
            phase_count?: number;
        } | null;
        recommended_modality: string | null;
        recommended_modality_label: string | null;
        selected_modality: string | null;
        selected_modality_label: string | null;
        presented_at: string | null;
        accepted_at: string | null;
        phases: Phase[];
    } | null;
    capability_options: Array<Record<string, unknown>>;
    modality_options: ModalityOption[];
    commercial_matrix_readiness: {
        ready: boolean;
        version: string | null;
        currency: string;
        missing_count: number;
        missing: string[];
    };
    endpoints: {
        back: string;
        create: string;
        phase_store: string;
        modality_select: string;
        commercial_generate: string;
        present: string;
        accept: string;
        phase_base: string;
    };
}>();

const page = usePage();

const errors = computed(
    () => (page.props.errors ?? {}) as Record<string, string>,
);

const isDraft = computed(() => props.plan?.status === 'draft');

const phases = computed(() => props.plan?.phases ?? []);

const hasGeneratedPlan = computed(() => phases.value.length > 0);

const selectedMilestones = computed(() => {
    if (!props.plan?.selected_modality) {
        return [];
    }

    return phases.value.flatMap((phase) =>
        phase.milestones.filter(
            (milestone) => milestone.modality === props.plan?.selected_modality,
        ),
    );
});

const modalityScenarios = computed(() =>
    props.modality_options.map((option) => {
        const estimates = phases.value
            .map((phase) =>
                phase.estimates.find(
                    (estimate) => estimate.modality === option.key,
                ),
            )
            .filter((estimate): estimate is Estimate => estimate !== undefined);

        const complete =
            phases.value.length > 0 && estimates.length === phases.value.length;

        const total = estimates.reduce(
            (sum, estimate) => sum + Number(estimate.price_amount ?? 0),
            0,
        );

        const durationsAreDays =
            estimates.length > 0 &&
            estimates.every(
                (estimate) => estimate.estimated_duration_unit === 'days',
            );

        const totalDurationDays = durationsAreDays
            ? estimates.reduce(
                  (sum, estimate) =>
                      sum + Number(estimate.estimated_duration_value ?? 0),
                  0,
              )
            : null;

        return {
            ...option,
            complete,
            estimates,
            total,
            totalDurationDays,
            currency: estimates[0]?.currency ?? 'DOP',
        };
    }),
);

const commercialScenariosComplete = computed(
    () =>
        phases.value.length > 0 &&
        modalityScenarios.value.length === props.modality_options.length &&
        modalityScenarios.value.every((scenario) => scenario.complete),
);

const selectedScenario = computed(() =>
    modalityScenarios.value.find(
        (item) => item.key === props.plan?.selected_modality,
    ),
);

const commercialReady = computed(() => {
    if (
        !props.plan ||
        !hasGeneratedPlan.value ||
        !props.plan.selected_modality ||
        !selectedScenario.value?.complete
    ) {
        return false;
    }

    return phases.value.every((phase) => {
        const estimate = phase.estimates.find(
            (item) => item.modality === props.plan?.selected_modality,
        );

        if (!estimate) {
            return false;
        }

        const milestones = phase.milestones.filter(
            (item) => item.modality === props.plan?.selected_modality,
        );

        if (milestones.length === 0) {
            return false;
        }

        const allocated = milestones.reduce(
            (sum, item) => sum + Number(item.billing_amount ?? 0),
            0,
        );

        return Math.abs(allocated - Number(estimate.price_amount ?? 0)) < 0.005;
    });
});

function statusLabel(status: string) {
    return (
        {
            draft: 'Borrador',
            under_review: 'En revisión',
            presented: 'Presentado',
            accepted: 'Aceptado',
            active: 'En ejecución',
            completed: 'Completado',
            cancelled: 'Cancelado',
        }[status] ?? status
    );
}

function money(value: number, currency = 'DOP') {
    return new Intl.NumberFormat('es-DO', {
        style: 'currency',
        currency,
        minimumFractionDigits: 2,
    }).format(value ?? 0);
}

function durationLabel(value: number, unit: string) {
    const labels: Record<string, string> = {
        days: value === 1 ? 'día' : 'días',
        weeks: value === 1 ? 'semana' : 'semanas',
        months: value === 1 ? 'mes' : 'meses',
    };

    return `${value} ${labels[unit] ?? unit}`;
}

function createOrGeneratePlan() {
    const message = props.plan
        ? '¿Generar automáticamente la estructura de este borrador desde su fuente?'
        : '¿Crear y generar automáticamente el Plan de Implementación desde la mejor fuente disponible?';

    if (!window.confirm(message)) {
        return;
    }

    router.post(props.endpoints.create, {}, { preserveScroll: true });
}

function generateCommercialScenarios() {
    if (
        !props.plan ||
        !isDraft.value ||
        !hasGeneratedPlan.value ||
        !props.commercial_matrix_readiness.ready
    ) {
        return;
    }

    const message = commercialScenariosComplete.value
        ? '¿Recalcular los tres escenarios comerciales con la matriz vigente? Esto actualizará únicamente las estimaciones del borrador.'
        : '¿Generar los escenarios Guiado, Asistido y Gestionado para este Plan?';

    if (!window.confirm(message)) {
        return;
    }

    router.post(
        props.endpoints.commercial_generate,
        {},
        {
            preserveScroll: true,
        },
    );
}

function presentPlan() {
    if (!commercialReady.value) {
        return;
    }

    if (
        !window.confirm(
            '¿Presentar este Plan al cliente? El tenant podrá revisarlo y aceptarlo desde su portal.',
        )
    ) {
        return;
    }

    router.post(props.endpoints.present, {}, { preserveScroll: true });
}
</script>

<template>
    <Head title="Plan de Implementación LAUDA 360" />

    <AppLayout
        :breadcrumbs="[
            {
                title: 'Diagnósticos 360',
                href: '/admin/diagnosis-requests',
            },
            {
                title: assessment.organization_name,
                href: `/admin/diagnosis-requests/${contact.id}`,
            },
            { title: 'Plan de Implementación' },
        ]"
    >
        <div class="space-y-6 p-4 md:p-6">
            <div class="flex flex-wrap items-start justify-between gap-4">
                <div>
                    <div class="flex flex-wrap gap-2">
                        <Badge variant="outline"> LAUDA 360 </Badge>

                        <Badge v-if="plan" variant="secondary">
                            V{{ plan.version }} ·
                            {{ statusLabel(plan.status) }}
                        </Badge>

                        <Badge v-if="plan?.autogeneration" variant="outline">
                            <Sparkles class="mr-1 size-3" />
                            Autogenerado
                        </Badge>
                    </div>

                    <h1 class="mt-3 text-2xl font-black">
                        Plan de Implementación
                    </h1>

                    <p
                        class="mt-1 max-w-3xl text-sm leading-6 text-muted-foreground"
                    >
                        El sistema convierte la fuente estratégica en un Plan
                        ejecutable. El administrador revisa y supervisa; no
                        construye manualmente el proyecto.
                    </p>
                </div>

                <Button as-child variant="outline">
                    <Link href="/admin/transformation-360/commercial-settings">
                        Tarifas T360
                    </Link>
                </Button>

                <Button as-child variant="outline">
                    <Link :href="endpoints.back">
                        <ArrowLeft class="mr-2 size-4" />
                        Volver
                    </Link>
                </Button>
            </div>

            <div
                v-if="Object.keys(errors).length"
                class="rounded-xl border border-destructive/40 bg-destructive/5 p-4"
            >
                <p class="font-bold">Revisa la configuración:</p>

                <ul class="mt-2 list-disc space-y-1 pl-5 text-sm">
                    <li v-for="(message, key) in errors" :key="key">
                        {{ message }}
                    </li>
                </ul>
            </div>

            <!-- 1 · FUENTE -->
            <Card>
                <CardHeader>
                    <div class="flex items-start gap-3">
                        <div class="rounded-xl border bg-muted/30 p-2">
                            <Route class="size-5" />
                        </div>

                        <div>
                            <CardTitle> 1. Fuente del Plan </CardTitle>

                            <CardDescription class="mt-1">
                                Se utiliza la fuente de mayor detalle disponible
                                sin obligar al cliente a comprar nuevamente
                                información ya adquirida.
                            </CardDescription>
                        </div>
                    </div>
                </CardHeader>

                <CardContent>
                    <div
                        v-if="plan?.source_type === 'internal_assessment'"
                        class="rounded-xl border p-4"
                    >
                        <p class="font-bold">Diagnóstico 360 publicado</p>

                        <p class="mt-1 text-sm text-muted-foreground">
                            El sistema utiliza un Roadmap interno de
                            planificación. No publica ni entrega un Roadmap
                            Detallado comercial que el cliente no haya
                            contratado.
                        </p>
                    </div>

                    <div v-else-if="roadmap" class="rounded-xl border p-4">
                        <div class="flex flex-wrap items-center gap-2">
                            <p class="font-bold">
                                Roadmap Detallado V{{ roadmap.version }}
                            </p>

                            <Badge variant="secondary">
                                Fuente prioritaria
                            </Badge>
                        </div>

                        <p class="mt-1 text-sm text-muted-foreground">
                            El cliente ya adquirió este entregable. Sus
                            prioridades, iniciativas y secuencia se reutilizan
                            para construir el Plan.
                        </p>
                    </div>

                    <div v-else class="rounded-xl border border-dashed p-4">
                        <p class="font-bold">Diagnóstico oficial</p>

                        <p class="mt-1 text-sm text-muted-foreground">
                            No existe un Roadmap Detallado publicado. El sistema
                            puede generar internamente la estructura necesaria
                            desde el Diagnóstico oficial.
                        </p>
                    </div>
                </CardContent>
            </Card>

            <!-- CREACIÓN / RECUPERACIÓN -->
            <Card v-if="!plan">
                <CardHeader>
                    <CardTitle> Generar Plan de Implementación </CardTitle>

                    <CardDescription>
                        El sistema generará automáticamente fases, objetivos,
                        capacidades, dependencias y entregables.
                    </CardDescription>
                </CardHeader>

                <CardContent class="space-y-4">
                    <div class="flex gap-3 rounded-xl border p-4 text-sm">
                        <LockKeyhole class="mt-0.5 size-5 shrink-0" />

                        <p class="text-muted-foreground">
                            Esta acción no crea facturas, pagos, suscripciones
                            ni inicia ejecución.
                        </p>
                    </div>

                    <Button @click="createOrGeneratePlan">
                        <Sparkles class="mr-2 size-4" />
                        Crear y generar Plan
                    </Button>
                </CardContent>
            </Card>

            <template v-else>
                <div class="grid gap-4 md:grid-cols-3">
                    <Card>
                        <CardHeader>
                            <CardDescription> Estado </CardDescription>

                            <CardTitle>
                                {{ statusLabel(plan.status) }}
                            </CardTitle>
                        </CardHeader>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardDescription>
                                Modalidad recomendada
                            </CardDescription>

                            <CardTitle class="text-lg">
                                {{
                                    plan.recommended_modality_label ??
                                    'Pendiente'
                                }}
                            </CardTitle>
                        </CardHeader>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardDescription>
                                Modalidad contratada
                            </CardDescription>

                            <CardTitle class="text-lg">
                                {{
                                    plan.selected_modality_label ??
                                    'Aún no seleccionada'
                                }}
                            </CardTitle>
                        </CardHeader>
                    </Card>
                </div>

                <Card v-if="isDraft && !hasGeneratedPlan" class="border-dashed">
                    <CardHeader>
                        <CardTitle>
                            Borrador anterior sin estructura
                        </CardTitle>

                        <CardDescription>
                            Este borrador fue creado antes del motor de
                            autogeneración. Puede completarse ahora sin borrarlo
                            ni crear una nueva versión.
                        </CardDescription>
                    </CardHeader>

                    <CardContent>
                        <Button @click="createOrGeneratePlan">
                            <Sparkles class="mr-2 size-4" />
                            Generar estructura automática
                        </Button>
                    </CardContent>
                </Card>

                <!-- 2 · PLAN GENERADO -->
                <Card>
                    <CardHeader>
                        <div class="flex items-start gap-3">
                            <div class="rounded-xl border bg-muted/30 p-2">
                                <Layers3 class="size-5" />
                            </div>

                            <div>
                                <CardTitle> 2. Plan generado </CardTitle>

                                <CardDescription class="mt-1">
                                    Fases y capacidades derivadas
                                    automáticamente de las prioridades y
                                    dependencias identificadas.
                                </CardDescription>
                            </div>
                        </div>
                    </CardHeader>

                    <CardContent v-if="hasGeneratedPlan" class="space-y-5">
                        <div
                            v-for="phase in phases"
                            :key="phase.id"
                            class="space-y-4 rounded-2xl border p-4 md:p-5"
                        >
                            <div
                                class="flex flex-wrap items-start justify-between gap-3"
                            >
                                <div>
                                    <div
                                        class="flex flex-wrap items-center gap-2"
                                    >
                                        <Badge variant="outline">
                                            Fase {{ phase.sequence }}
                                        </Badge>

                                        <Badge
                                            v-if="phase.horizon"
                                            variant="secondary"
                                        >
                                            <Clock3 class="mr-1 size-3" />
                                            {{ phase.horizon }}
                                        </Badge>

                                        <Badge
                                            v-if="phase.autogenerated"
                                            variant="outline"
                                        >
                                            <Sparkles class="mr-1 size-3" />
                                            Generada
                                        </Badge>
                                    </div>

                                    <h3 class="mt-2 text-lg font-black">
                                        {{ phase.name }}
                                    </h3>

                                    <p
                                        v-if="phase.objective"
                                        class="mt-2 max-w-4xl text-sm leading-6 text-muted-foreground"
                                    >
                                        {{ phase.objective }}
                                    </p>
                                </div>
                            </div>

                            <div>
                                <p
                                    class="text-xs font-black tracking-wide uppercase"
                                >
                                    Capacidades
                                </p>

                                <div class="mt-2 grid gap-3 md:grid-cols-2">
                                    <div
                                        v-for="capability in phase.capabilities"
                                        :key="capability.id"
                                        class="rounded-xl border p-3"
                                    >
                                        <div
                                            class="flex flex-wrap items-center gap-2"
                                        >
                                            <p class="font-bold">
                                                {{
                                                    capability.capability_label
                                                }}
                                            </p>

                                            <Badge
                                                v-if="
                                                    capability.kind ===
                                                    'professional_service'
                                                "
                                                variant="secondary"
                                            >
                                                Servicio profesional
                                            </Badge>

                                            <Badge
                                                v-else-if="
                                                    capability.subscription_candidate
                                                "
                                                variant="outline"
                                            >
                                                Solución LAUDAAPI
                                            </Badge>
                                        </div>

                                        <p
                                            v-if="capability.summary"
                                            class="mt-2 text-xs leading-5 text-muted-foreground"
                                        >
                                            {{ capability.summary }}
                                        </p>

                                        <p
                                            v-if="
                                                capability.kind ===
                                                'professional_service'
                                            "
                                            class="mt-2 text-[11px] font-semibold text-muted-foreground"
                                        >
                                            {{
                                                'Se cotiza dentro del Plan · no genera suscripción recurrente.'
                                            }}
                                        </p>

                                        <p
                                            v-else-if="
                                                capability.subscription_candidate
                                            "
                                            class="mt-2 text-[11px] font-semibold text-muted-foreground"
                                        >
                                            La suscripción de la solución solo
                                            puede activarse después de su
                                            Go-Live.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div
                                v-if="phase.dependencies.length"
                                class="rounded-xl bg-muted/30 p-3"
                            >
                                <p
                                    class="text-xs font-black tracking-wide uppercase"
                                >
                                    Dependencias
                                </p>

                                <div class="mt-2 flex flex-wrap gap-2">
                                    <Badge
                                        v-for="dependency in phase.dependencies"
                                        :key="dependency"
                                        variant="outline"
                                    >
                                        {{ dependency }}
                                    </Badge>
                                </div>
                            </div>

                            <div v-if="phase.deliverables.length">
                                <p
                                    class="text-xs font-black tracking-wide uppercase"
                                >
                                    Entregables previstos
                                </p>

                                <ul
                                    class="mt-2 grid gap-2 text-sm text-muted-foreground md:grid-cols-2"
                                >
                                    <li
                                        v-for="deliverable in phase.deliverables"
                                        :key="deliverable"
                                        class="flex gap-2"
                                    >
                                        <CheckCircle2
                                            class="mt-0.5 size-4 shrink-0"
                                        />
                                        <span>
                                            {{ deliverable }}
                                        </span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </CardContent>

                    <CardContent v-else class="text-sm text-muted-foreground">
                        La estructura todavía no ha sido generada.
                    </CardContent>
                </Card>

                <!-- 3 · MODALIDADES -->
                <Card>
                    <CardHeader>
                        <div class="flex items-start gap-3">
                            <div class="rounded-xl border bg-muted/30 p-2">
                                <UsersRound class="size-5" />
                            </div>

                            <div>
                                <CardTitle>
                                    3. Modalidades de ejecución
                                </CardTitle>

                                <CardDescription class="mt-1">
                                    El Plan funcional es el mismo. Lo que cambia
                                    es quién ejecuta, el nivel de intervención
                                    de LAUDA, la duración y la inversión.
                                </CardDescription>
                            </div>
                        </div>
                    </CardHeader>

                    <CardContent class="grid gap-4 lg:grid-cols-3">
                        <div
                            v-for="option in modality_options"
                            :key="option.key"
                            class="relative rounded-2xl border p-4"
                            :class="{
                                'ring-2 ring-primary':
                                    option.key === plan.selected_modality,
                            }"
                        >
                            <Badge
                                v-if="option.key === plan.recommended_modality"
                                class="mb-3"
                            >
                                Recomendada
                            </Badge>

                            <Badge
                                v-if="option.key === plan.selected_modality"
                                variant="secondary"
                                class="mb-3 ml-2"
                            >
                                Seleccionada
                            </Badge>

                            <h3 class="text-lg font-black">
                                {{ option.label }}
                            </h3>

                            <p
                                class="mt-2 text-sm leading-6 text-muted-foreground"
                            >
                                {{ option.description }}
                            </p>

                            <div class="mt-4">
                                <p
                                    class="text-xs font-black tracking-wide uppercase"
                                >
                                    Incluye
                                </p>

                                <ul class="mt-2 space-y-2 text-sm">
                                    <li
                                        v-for="item in option.includes"
                                        :key="item"
                                        class="flex gap-2"
                                    >
                                        <CheckCircle2
                                            class="mt-0.5 size-4 shrink-0"
                                        />
                                        <span>{{ item }}</span>
                                    </li>
                                </ul>
                            </div>

                            <div class="mt-4 space-y-3 border-t pt-4 text-sm">
                                <div>
                                    <p class="font-bold">LAUDA</p>

                                    <p class="text-muted-foreground">
                                        {{ option.lauda_role }}
                                    </p>
                                </div>

                                <div>
                                    <p class="font-bold">Cliente</p>

                                    <p class="text-muted-foreground">
                                        {{ option.client_role }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <!-- 4 · INVERSIÓN -->
                <Card>
                    <CardHeader>
                        <div class="flex items-start gap-3">
                            <div class="rounded-xl border bg-muted/30 p-2">
                                <Gauge class="size-5" />
                            </div>

                            <div>
                                <CardTitle> 4. Inversión y tiempo </CardTitle>

                                <CardDescription class="mt-1">
                                    Se compararán las tres modalidades sobre
                                    exactamente el mismo Plan antes de que el
                                    tenant seleccione una.
                                </CardDescription>

                                <div
                                    v-if="isDraft && hasGeneratedPlan"
                                    class="mt-4 flex flex-wrap items-center gap-3"
                                >
                                    <Button
                                        :variant="
                                            commercialScenariosComplete
                                                ? 'outline'
                                                : 'default'
                                        "
                                        :disabled="
                                            !commercial_matrix_readiness.ready
                                        "
                                        @click="generateCommercialScenarios"
                                    >
                                        <Sparkles class="mr-2 size-4" />

                                        {{
                                            commercialScenariosComplete
                                                ? 'Recalcular escenarios comerciales'
                                                : 'Generar escenarios comerciales'
                                        }}
                                    </Button>

                                    <span
                                        v-if="
                                            !commercial_matrix_readiness.ready
                                        "
                                        class="text-xs text-muted-foreground"
                                    >
                                        La matriz comercial tiene
                                        {{
                                            commercial_matrix_readiness.missing_count
                                        }}
                                        campos pendientes.
                                    </span>

                                    <span
                                        v-else-if="
                                            commercialScenariosComplete
                                        "
                                        class="text-xs text-muted-foreground"
                                    >
                                        Los tres escenarios están calculados.
                                        Solo pueden recalcularse mientras el
                                        Plan permanezca en borrador.
                                    </span>
                                </div>

                            </div>
                        </div>
                    </CardHeader>

                    <CardContent class="grid gap-4 lg:grid-cols-3">
                        <div
                            v-for="scenario in modalityScenarios"
                            :key="scenario.key"
                            class="rounded-2xl border p-4"
                        >
                            <div
                                class="flex items-center justify-between gap-2"
                            >
                                <p class="font-black">
                                    {{ scenario.label }}
                                </p>

                                <Badge
                                    :variant="
                                        scenario.complete
                                            ? 'secondary'
                                            : 'outline'
                                    "
                                >
                                    {{
                                        scenario.complete
                                            ? 'Calculado'
                                            : 'Pendiente'
                                    }}
                                </Badge>
                            </div>

                            <template v-if="scenario.complete">
                                <p class="mt-4 text-2xl font-black">
                                    {{
                                        money(scenario.total, scenario.currency)
                                    }}
                                </p>

                                <p
                                    v-if="
                                        scenario.totalDurationDays !== null
                                    "
                                    class="mt-1 flex items-center gap-1 text-sm font-semibold text-muted-foreground"
                                >
                                    <Clock3 class="size-4" />
                                    Duración estimada total:
                                    {{
                                        durationLabel(
                                            scenario.totalDurationDays,
                                            'days',
                                        )
                                    }}
                                </p>


                                <div
                                    class="mt-4 space-y-2 border-t pt-4 text-xs text-muted-foreground"
                                >
                                    <div
                                        v-for="(
                                            estimate, index
                                        ) in scenario.estimates"
                                        :key="index"
                                        class="flex justify-between gap-3"
                                    >
                                        <span> Fase {{ index + 1 }} </span>

                                        <span class="text-right">
                                            {{
                                                money(
                                                    estimate.price_amount,
                                                    estimate.currency,
                                                )
                                            }}
                                            ·
                                            {{
                                                durationLabel(
                                                    estimate.estimated_duration_value,
                                                    estimate.estimated_duration_unit,
                                                )
                                            }}
                                        </span>
                                    </div>
                                </div>
                            </template>

                            <div
                                v-else
                                class="mt-4 rounded-xl bg-muted/30 p-3 text-sm text-muted-foreground"
                            >
                                La matriz comercial todavía debe calcular
                                automáticamente precio y tiempo para esta
                                modalidad.
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <!-- 5 · HITOS -->
                <Card>
                    <CardHeader>
                        <CardTitle> 5. Hitos y condiciones </CardTitle>

                        <CardDescription>
                            Los hitos se generan después de seleccionar una
                            modalidad y deben sumar exactamente el valor de cada
                            fase.
                        </CardDescription>
                    </CardHeader>

                    <CardContent>
                        <div
                            v-if="!plan.selected_modality"
                            class="rounded-xl border border-dashed p-4 text-sm text-muted-foreground"
                        >
                            Primero se calcularán y compararán las tres
                            modalidades. Después el tenant seleccionará una y el
                            sistema generará sus hitos.
                        </div>

                        <div
                            v-else-if="selectedMilestones.length === 0"
                            class="rounded-xl border border-dashed p-4 text-sm text-muted-foreground"
                        >
                            Modalidad seleccionada:
                            <strong> {{ plan.selected_modality_label }} </strong
                            >. Los hitos todavía están pendientes de generación
                            automática.
                        </div>

                        <div v-else class="space-y-3">
                            <div
                                v-for="milestone in selectedMilestones"
                                :key="milestone.id"
                                class="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-sm"
                            >
                                <span>
                                    {{ milestone.sequence }}.
                                    {{ milestone.name }}
                                </span>

                                <span class="font-bold">
                                    {{
                                        money(
                                            milestone.billing_amount,
                                            milestone.currency,
                                        )
                                    }}
                                    ·
                                    {{ milestone.billing_percentage }}%
                                </span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <!-- 6 · PRESENTACIÓN -->
                <Card>
                    <CardHeader>
                        <div class="flex items-start gap-3">
                            <div class="rounded-xl border bg-muted/30 p-2">
                                <UserRoundCheck class="size-5" />
                            </div>

                            <div>
                                <CardTitle> 6. Presentación </CardTitle>

                                <CardDescription class="mt-1">
                                    LAUDA supervisa el resultado. El cliente
                                    revisa y acepta el Plan desde su propio
                                    portal.
                                </CardDescription>
                            </div>
                        </div>
                    </CardHeader>

                    <CardContent class="space-y-4">
                        <div
                            v-if="isDraft && !commercialReady"
                            class="rounded-xl border border-dashed p-4 text-sm text-muted-foreground"
                        >
                            El Plan todavía no está listo para presentarse. Debe
                            tener estructura, modalidad seleccionada,
                            precio/tiempo y distribución completa de hitos.
                        </div>

                        <Button
                            v-if="isDraft"
                            :disabled="!commercialReady"
                            @click="presentPlan"
                        >
                            <Send class="mr-2 size-4" />
                            Presentar Plan al tenant
                        </Button>

                        <div
                            v-else-if="plan.status === 'presented'"
                            class="rounded-xl border p-4"
                        >
                            <p class="font-bold">Plan presentado</p>

                            <p class="mt-1 text-sm text-muted-foreground">
                                Está pendiente de revisión y aceptación por el
                                tenant.
                            </p>
                        </div>
                    </CardContent>
                </Card>

                <Card
                    v-if="
                        ['accepted', 'active', 'completed'].includes(
                            plan.status,
                        )
                    "
                >
                    <CardHeader>
                        <CardTitle> Ejecución </CardTitle>

                        <CardDescription>
                            La ejecución comienza únicamente después de la
                            aceptación del Plan.
                        </CardDescription>
                    </CardHeader>

                    <CardContent>
                        <Button as-child>
                            <Link
                                :href="`/admin/diagnosis-requests/${contact.id}/implementation-plan/execution`"
                            >
                                Gestionar ejecución y Go-Live
                            </Link>
                        </Button>
                    </CardContent>
                </Card>

                <div
                    class="rounded-2xl border bg-muted/20 p-4 text-sm text-muted-foreground"
                >
                    <FileText class="mr-2 inline size-4" />
                    El Plan de Implementación es un proyecto de transformación.
                    Su aceptación no crea una suscripción. Las soluciones
                    recurrentes solo pueden activarse posteriormente mediante su
                    propio Go-Live.
                </div>
            </template>
        </div>
    </AppLayout>
</template>
